config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"

  get '/' => 'home#index'

  get 'terms' => 'pages#terms', as: :terms
  get 'about' => 'pages#about', as: :about

  resource :contacts, only: [:new, :create], path_names: { :new => '' }
  
  resources :articles do
    resources :comments
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, :text, presence: true
  has_many :comments
  
  def subject
    title
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :author, :body, presence: true
  belongs_to :article
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :message, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  #has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  before_filter :configure_permitted_parameters, if: :devise_controller?
  
  private
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :authenticate_user!, :only => [:new, :create, :edit, :delete]

  def index
    @articles = Article.order('created_at DESC')
  end
  
  def show
    @article = Article.find(params[:id])
    @comments = @article.comments.order('created_at DESC')
  end
  
  def new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article
    else
      render action: 'new'
    end
  end
  
  def edit
    @article = Article.find(params[:id])
  end
  
  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article
    else
      render action: 'edit'
    end
  end
  
  def destroy
    @article = Article.find(params[:id])
    if current_user == @article.user
      if @article.destroy
      redirect_to articles_path
      else
        render action: 'index'
      end
      
    end
  end
  
  private

  def article_params
    params.require(:article).permit(:title, :text) #указываем только то, что получаем с клиената, остальные поля запрещены к передаче
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  before_filter :authenticate_user!, :only => [:create]

  def create
    @article = Article.find(params[:article_id])
    @c = @article.comments.create(comment_params)
    @c.author = current_user.username
    @c.save

    redirect_to article_path(@article)
  end

  private

  def comment_params
    params.require(:comment).permit(:author, :body)
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  
  def new
  end
  
  def create
    @contact = Contact.new(content_params)
    if @contact.valid?
      @contact.save
    else
      render action: 'new'
    end
  end

  private

  def content_params
    params.require(:contact).permit(:name, :phone, :email, :message)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def terms
  end

  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/edit.html.erb
<h1>Edit article: "<%= @article.title %>"</h1>
<br>

<%= form_for :article, url: article_path(@article), method: :put do |f| %>
    <p>
      <%= f.label :title %> <br>
      <%= f.text_field :title %>
    </p>
    <p>
      <%= f.label :text %> <br>
      <%= f.text_area :text %>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/articles/index.html.erb
<% provide(:articles_active, 'active') %>

<%= link_to 'Add Article', new_article_path, class: "btn btn-lg btn-success" %>
<br>
<br></br>

<h1>List of Articles:</h1>



<% @articles.each do |article| %>.
    <h2><%= article.title %></h2>
    <p><%= article.text %></p>
    <p>
      <%= link_to 'Show', article_path(article)  %>
      <% if user_signed_in? %>
      | <%= link_to 'Edit', edit_article_path(article)  %> |
      <%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: 'Are You Sure?'}  %>
      <% else %>
        <%= '' %>
      <% end %>
    </p>
    <hr>
<% end %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= form_for :article, url: articles_path do |f| %>
    <p>
      <%= f.label :title %> <br>
      <%= f.text_field :title %>
    </p>
    <p>
      <%= f.label :text %> <br>
      <%= f.text_area :text %>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.text %></p>

<div style="max-width: 400px">

<%= form_for ([@article, @article.comments.build]) do |f| %>
    <p>
      <%= f.label :body %> <br>
      <%= f.text_area :body, class: 'form-control' %>
    </p>
    <p>
      <%= f.submit class: 'btn btn-block' %>
    </p>
<% end %>
</div>

<br>
<p class="h2">Comments:</p>
<% @comments.each do |comment| %>
    <h5>Author: <span style="color:grey;"><%= comment.author %></span></h5>
    <small style="color:grey;">Comment: <%= comment.created_at.localtime.strftime('%d/%m/%Y %H:%M') %></small>
    <p><%= comment.body %></p>
    <hr>
<% end %>

app/views/contacts/create.html.erb
<% provide(:contacts_active, 'active') %>

<h1>Thank you!</h1>

<p>Article has been created!</p>

<%= link_to 'Show all articles', articles_path %>">

app/views/contacts/new.html.erb
<% provide(:contacts_active, 'active') %>

<h1>Contact us</h1>

<br>

<%= form_for :contact, url: contacts_path do |f| %>
    <p>
      <% if @contact && @contact.errors.any? %>
        <ul>
          <% @contact.errors.full_messages.each do |msg| %>
            <li style="color:red;">
              <%= msg %>
            </li>
          <% end %>
        </ul>
      <% end %>
    </p>
    <p>
      <%= f.label :name %> <br>
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :phone %> <br>
      <%= f.text_field :phone %>
    </p>
    <p>
      <%= f.label :email %> <br>
      <%= f.text_field :email %>
    </p>
    <p>
      <%= f.label :message %> <br>
      <%= f.text_area :message %>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/home/contacts.html.erb
<% provide(:contacts_active, 'active') %>

<h1>Home#contacts</h1>
<p>Find me in app/views/home/contacts.html.erb</p>

app/views/home/index.html.erb
<h1>Home#index!!!</h1>
<p>Find me in app/views/home/index.html.erb</p>

<img src="https://placeimg.com/300/300/any" alt="">

<p>Blue bottle vexillologist gochujang, food truck pour-over succulents heirloom typewriter jean shorts. Actually lo-fi kitsch, cred kogi shoreditch taxidermy authentic austin snackwave edison bulb echo park pitchfork leggings. Hot chicken fam celiac skateboard yuccie. </p>

<p>Green juice artisan salvia snackwave. Flannel jean shorts polaroid food truck, pickled shabby chic banh mi VHS enamel pin subway tile selvage twee. Next level lomo portland neutra, glossier whatever vaporware tilde ramps la croix bitters truffaut migas VHS asymmetrical. Direct trade coloring book sartorial flexitarian bespoke.</p>

<button class="btn btn-lg btn-success">Test Button</button>

app/views/layouts/_navbar.html.erb
<div class="container">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">First<span style="font-weight: bold;">Ruby</span>Site</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'Articles', articles_path, class: "nav-link #{yield(:articles_active)}" %>
      </li>
      <li class="nav-item">
        <%= link_to 'About', about_path, class: "nav-link #{yield(:about_active)}" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Terms & Conditions', terms_path, class: "nav-link #{yield(:terms_active)}" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Contact Us', contacts_path, class: "nav-link #{yield(:contacts_active)}" %>
      </li>
    </ul>
    <ul class="navbar-nav">
      <li class="nav-item">
      <% if user_signed_in? %>
          <span>Hello, <%= current_user.username %>! </span>
          <%= link_to 'Log out', destroy_user_session_path, :method => :delete %>
      <% else %>
          <%= link_to 'Log In', new_user_session_path %> or <%= link_to 'Sign In', new_user_registration_path %>
      <% end %>
      </li>
    </ul>
  </div>
</nav>
</div>  <!--container-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsFirst</title>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <%= render 'layouts/navbar' %>

  <div class="container">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </div>

  </body>
</html>

app/views/pages/about.html.erb
<% provide(:about_active, 'active') %>

<h1>About Us</h1>

<br>

<p>Vinyl hell of tote bag, pork belly prism twee knausgaard everyday carry raw denim fashion axe lyft. Hot chicken flannel man bun 8-bit. Hot chicken squid taiyaki, pok pok af normcore austin. Activated charcoal aesthetic austin single-origin coffee vexillologist. Put a bird on it semiotics stumptown, poke XOXO crucifix photo booth shoreditch heirloom occupy seitan pitchfork bushwick. Knausgaard iPhone edison bulb banh mi heirloom la croix selvage quinoa church-key vegan next level vape stumptown pour-over. Pabst heirloom venmo migas cray pickled organic selvage cornhole bitters ennui DIY coloring book seitan.</p>

 <p>Locavore shoreditch humblebrag, sustainable succulents chia put a bird on it letterpress. Hashtag cornhole affogato, small batch chia plaid godard direct trade bicycle rights. Sriracha kale chips cloud bread lyft lo-fi paleo, bespoke sustainable offal austin raw denim distillery cred copper mug tumeric. Forage cray YOLO succulents four loko, man braid ethical. Disrupt freegan neutra health goth gentrify edison bulb unicorn typewriter iPhone.</p>

app/views/pages/terms.html.erb
<% provide(:terms_active, 'active') %>

<h1>Terms and Conditions</h1>

<br>

<p>
  Try-hard roof party locavore coloring book. Hoodie sartorial microdosing drinking vinegar. Occupy truffaut leggings hammock. Fingerstache fam taiyaki shabby chic kinfolk tattooed affogato letterpress pinterest cliche. Man braid whatever street art poke. Affogato ugh semiotics before they sold out microdosing health goth hexagon tote bag vape. Mixtape lumbersexual thundercats, adaptogen slow-carb fingerstache brooklyn raclette.
</p>
<p>

</p>Hot chicken stumptown migas bespoke, wolf tofu pork belly unicorn banjo leggings DIY venmo. Intelligentsia blog dreamcatcher, iceland neutra hashtag hella prism vexillologist 90's cronut echo park. Sustainable tumblr tousled roof party tattooed iceland snackwave selvage fam kitsch next level crucifix jean shorts. Kickstarter bitters kale chips glossier put a bird on it vaporware lumbersexual chambray, artisan taxidermy blog. Hammock woke cardigan meh tumeric. Migas kogi paleo echo park fashion axe lomo. Marfa butcher mixtape hammock. Photo booth banjo four dollar toast trust fund lumbersexual.